version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $( aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=408812974241.dkr.ecr.us-east-1.amazonaws.com/express-7edge
   build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  express-7edge .
      - docker tag express-7edge:latest 408812974241.dkr.ecr.us-east-1.amazonaws.com/express-7edge:latest 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push  408812974241.dkr.ecr.us-east-1.amazonaws.com/express-7edge:latest
      
     
    
